title: Apache ZooKeeper
url: "https://zookeeper.apache.org"

highlighter: pygments
markdown: kramdown
kramdown:
  entity_output: symbol
permalink: none

exclude:
    - README.md
    - content
    - doc